services:
  app:
    build:
      context: .
    image: prathitagarje/nodejs:latest
    container_name: nodejsapp
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MESSAGE=Hello from Compose!
    init: true
    restart: unless-stopped
